# Generated by Django 5.0.1 on 2024-01-29 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed')),
                ('address', models.CharField(default='nema')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('company', models.IntegerField(default=-1)),
                ('equipment', models.ManyToManyField(to='hospital_contract.equipment')),
                ('hospital', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='hospital_contract.hospital')),
            ],
        ),
    ]
