# Generated by Django 4.2.7 on 2024-01-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(default='active', max_length=15),
        ),
    ]
